const schemaStatements = [
  `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'agent' CHECK (role IN ('agent', 'admin', 'management')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    phone VARCHAR(20),
    contact_no VARCHAR(20),
    emergency_contact VARCHAR(20),
    manager_name VARCHAR(100),
    department VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
  );
  `,
  `CREATE INDEX IF NOT EXISTS idx_role ON users(role);`,
  `CREATE INDEX IF NOT EXISTS idx_status ON users(status);`,
  `CREATE INDEX IF NOT EXISTS idx_contact_no ON users(contact_no);`,

  `
  CREATE TABLE IF NOT EXISTS camera_serials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR(50) NOT NULL UNIQUE,
    item_no VARCHAR(50) NOT NULL,
    item_description VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
  );
  `,
  `CREATE INDEX IF NOT EXISTS idx_serial_number ON camera_serials(serial_number);`,
  `CREATE INDEX IF NOT EXISTS idx_item_no ON camera_serials(item_no);`,

  `
  CREATE TABLE IF NOT EXISTS complaints (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no VARCHAR(20) NOT NULL UNIQUE,
    agent_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    customer_email VARCHAR(100) NOT NULL,
    customer_address VARCHAR(255) NOT NULL,
    customer_account_no VARCHAR(50),
    serial_no VARCHAR(50),
    device_model VARCHAR(100) NOT NULL,
    issue_description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Booked', 'In-Progress', 'Replaced', 'Rejected')),
    priority VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    sla_duration INTEGER NOT NULL DEFAULT 48,
    sla_deadline TIMESTAMP,
    sla_status VARCHAR(20) NOT NULL DEFAULT 'Within SLA' CHECK (sla_status IN ('Within SLA', 'At Risk', 'Breached')),
    sla_breached_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
  );
  `,
  `CREATE INDEX IF NOT EXISTS idx_ticket_no ON complaints(ticket_no);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_id ON complaints(agent_id);`,
  `CREATE INDEX IF NOT EXISTS idx_status ON complaints(status);`,
  `CREATE INDEX IF NOT EXISTS idx_created_at ON complaints(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_serial_no ON complaints(serial_no);`,
  `CREATE INDEX IF NOT EXISTS idx_complaint_status_date ON complaints(status, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_created ON complaints(agent_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_recent_complaints ON complaints(created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_sla_status ON complaints(sla_status);`,
  `CREATE INDEX IF NOT EXISTS idx_sla_deadline ON complaints(sla_deadline);`,
  `CREATE INDEX IF NOT EXISTS idx_sla_breached ON complaints(sla_breached_at);`,

  `
  CREATE TABLE IF NOT EXISTS manufacturer_updates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id INTEGER NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
    booking_id VARCHAR(50) NOT NULL,
    booked_date DATE NOT NULL,
    manufacturer_status VARCHAR(100),
    reference_no VARCHAR(50),
    notes TEXT,
    customer_account_no VARCHAR(50),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
  );
  `,
  `CREATE INDEX IF NOT EXISTS idx_complaint_id ON manufacturer_updates(complaint_id);`,
  `CREATE INDEX IF NOT EXISTS idx_booking_id ON manufacturer_updates(booking_id);`,

  `
  CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id INTEGER,
    old_values JSONB,
    new_values JSONB,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    "timestamp" TIMESTAMP NOT NULL DEFAULT NOW()
  );
  `,
  `CREATE INDEX IF NOT EXISTS idx_timestamp ON audit_logs("timestamp");`,
  `CREATE INDEX IF NOT EXISTS idx_entity ON audit_logs(entity_type, entity_id);`,
  `CREATE INDEX IF NOT EXISTS idx_action ON audit_logs(action);`,
  `CREATE INDEX IF NOT EXISTS idx_user_id ON audit_logs(user_id);`,

  `
  CREATE TABLE IF NOT EXISTS sla_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority VARCHAR(20) NOT NULL UNIQUE CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    duration_hours INTEGER NOT NULL,
    at_risk_percentage INTEGER NOT NULL DEFAULT 80,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
  );
  `,

  `
  CREATE TABLE IF NOT EXISTS sla_audit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id INTEGER NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
    old_status VARCHAR(50),
    new_status VARCHAR(50),
    triggered_at TIMESTAMP NOT NULL DEFAULT NOW(),
    reason VARCHAR(255)
  );
  `,
  `CREATE INDEX IF NOT EXISTS idx_sla_audit_complaint_id ON sla_audit(complaint_id);`,
  `CREATE INDEX IF NOT EXISTS idx_triggered_at ON sla_audit(triggered_at);`,

  `
  CREATE OR REPLACE FUNCTION set_updated_at()
  RETURNS TRIGGER AS $$
  BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;
  `,

  `DROP TRIGGER IF EXISTS set_users_updated_at ON users;`,
  `CREATE TRIGGER set_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();`,
  `DROP TRIGGER IF EXISTS set_camera_serials_updated_at ON camera_serials;`,
  `CREATE TRIGGER set_camera_serials_updated_at BEFORE UPDATE ON camera_serials FOR EACH ROW EXECUTE FUNCTION set_updated_at();`,
  `DROP TRIGGER IF EXISTS set_complaints_updated_at ON complaints;`,
  `CREATE TRIGGER set_complaints_updated_at BEFORE UPDATE ON complaints FOR EACH ROW EXECUTE FUNCTION set_updated_at();`,
  `DROP TRIGGER IF EXISTS set_manufacturer_updates_updated_at ON manufacturer_updates;`,
  `CREATE TRIGGER set_manufacturer_updates_updated_at BEFORE UPDATE ON manufacturer_updates FOR EACH ROW EXECUTE FUNCTION set_updated_at();`,
  `DROP TRIGGER IF EXISTS set_sla_config_updated_at ON sla_config;`,
  `CREATE TRIGGER set_sla_config_updated_at BEFORE UPDATE ON sla_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();`,
];

module.exports = {
  schemaStatements,
};
